version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: employee_data_server
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env

    networks:
      - shared-apps

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: employee_data_client
    ports:
      - "5173:5173"
    env_file:
      - ./client/.env
    depends_on:
      - server
    networks:
      - shared-apps

networks:
  shared-apps:
    external: true
